export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';
export const SET_PAGE_NUM = 'SET_PAGE_NUM';

export const FETCH_PRODUCTS_DETAILS = 'FETCH_PRODUCTS_DETAILS';
export const FETCH_PRODUCTS_DETAILS_SUCCESS = 'FETCH_PRODUCTS_DETAILS_SUCCESS';
export const FETCH_PRODUCTS_DETAILS_FAILED = 'FETCH_PRODUCTS_DETAILS_FAILED';